CREATE TABLE `entry_requests` (
	`id` varchar(64) NOT NULL,
	`requestNumber` varchar(100) NOT NULL,
	`bpCompanyId` varchar(64) NOT NULL,
	`bpUserId` varchar(64) NOT NULL,
	`equipmentId` varchar(64) NOT NULL,
	`workerId` varchar(64) NOT NULL,
	`purpose` text,
	`requestedStartDate` datetime,
	`requestedEndDate` datetime,
	`status` enum('bp_requested','owner_reviewing','owner_approved','bp_reviewing','bp_approved','ep_reviewing','ep_approved','rejected') NOT NULL DEFAULT 'bp_requested',
	`ownerApprovedAt` datetime,
	`ownerApprovedBy` varchar(64),
	`ownerComment` text,
	`bpApprovedAt` datetime,
	`bpApprovedBy` varchar(64),
	`workPlanFileUrl` varchar(500),
	`bpComment` text,
	`epApprovedAt` datetime,
	`epApprovedBy` varchar(64),
	`epComment` text,
	`rejectedAt` datetime,
	`rejectedBy` varchar(64),
	`rejectReason` text,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `entry_requests_id` PRIMARY KEY(`id`)
);
